version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules_dev:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
    command: npm run dev -- --host

  frontend-prod:
    build:
      context: .
      target: runner
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3000
    command: serve -s dist -l 4173

volumes:
  node_modules_dev: 