services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-zuno_jwt_secret_2025}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    depends_on:
      - backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:3000}
    ports:
      - "4173:4173"
    restart: unless-stopped


