services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-production}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: sh -c "npx prisma generate && npm run start"
    volumes:
      - .:/app
      - /app/node_modules 